name: Build on PR to master

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Should be a reusable workflow (build)
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Restore wrapper cache
        uses: actions/cache@v1.0.3
        with:
          path: ~/.gradle/wrapper/dists/
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Add google-services.json
        env:
          GOOGLE_SERVICES_CONFIG: ${{ secrets.GOOGLE_SERVICES_CONFIG }}
        run: echo $GOOGLE_SERVICES_CONFIG > app/google-services.json

      - name: Add release keystore
        env:
          APP_KEYSTORE: ${{ secrets.APP_KEYSTORE }}
        run: echo $APP_KEYSTORE | base64 --decode > app/logistics.keystore

      - name: Add release keystore credentials
        env:
          KEYSTORE_CREDENTIALS: ${{ secrets.KEYSTORE_CREDENTIALS }}
        run: echo $KEYSTORE_CREDENTIALS | base64 --decode >> gradle.properties

      - name: Add Google Places API key
        env:
          PLACES_API_KEY: ${{secrets.PLACES_API_KEY}}
        run: echo "placesApiKey=$PLACES_API_KEY" >> gradle.properties

      - name: Add Branch.io API key
        env:
          BRANCH_IO_API_KEY: ${{secrets.BRANCH_IO_API_KEY}}
        run: echo "logisticsBranchKey=$BRANCH_IO_API_KEY" >> gradle.properties

      - name: Add Hypertrack services API key
        env:
          SERVICES_API_KEY: ${{secrets.SERVICES_API_KEY}}
        run: echo "servicesApiKey=$SERVICES_API_KEY" >> gradle.properties

      - name: Add Hypertrack GraphQL API key
        env:
          GRAPHQL_API_KEY: ${{secrets.GRAPHQL_API_KEY}}
        run: echo "graphqlApiKey=$GRAPHQL_API_KEY" >> gradle.properties

      - name: Build with Gradle
        run: ./gradlew build
