name: Build on PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout & environment setup
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      # Env and temp files setup
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_CONFIG: ${{ secrets.GOOGLE_SERVICES_CONFIG }}
        run: echo $GOOGLE_SERVICES_CONFIG > app/google-services.json
      - name: Decode release keystore
        env:
          APP_KEYSTORE: ${{ secrets.APP_KEYSTORE }}
        run: echo $APP_KEYSTORE | base64 --decode > app/logistics.keystore
      - name: Keystore credentials
        env:
          KEYSTORE_CREDENTIALS: ${{ secrets.KEYSTORE_CREDENTIALS }}
        run: echo $KEYSTORE_CREDENTIALS | base64 --decode >> gradle.properties
      - name: Google Places API key
        env:
          PLACES_API_KEY: ${{secrets.PLACES_API_KEY}}
        run: echo $PLACES_API_KEY >> gradle.properties     
      # Build itself
      - name: Build with Gradle
        run: ./gradlew build
