name: Release Build

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Should be a reusable workflow (build)
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Restore wrapper cache
        uses: actions/cache@v1.0.3
        with:
          path: ~/.gradle/wrapper/dists/
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Add google-services.json
        env:
          GOOGLE_SERVICES_CONFIG: ${{ secrets.GOOGLE_SERVICES_CONFIG }}
        run: echo $GOOGLE_SERVICES_CONFIG > app/google-services.json

      # Release keystore

      - name: Add release keystore
        env:
          APP_KEYSTORE: ${{ secrets.APP_KEYSTORE }}
        run: echo $APP_KEYSTORE | base64 --decode > visits.keystore; pwd; ls;

      - name: Add release keystore path
        run: echo "visitsKeystorePath=../visits.keystore" >> local.properties

      - name: Add release keystore data
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        run: echo "visitsKeystorePassword=$KEYSTORE_PASSWORD" >> local.properties;
          echo "visitsKeyAlias=$KEYSTORE_KEY_ALIAS" >> local.properties;
          echo "visitsKeyPassword=$KEYSTORE_KEY_PASSWORD" >> local.properties;

      # Misc

      - name: Add Google Places API key
        env:
          PLACES_API_KEY: ${{secrets.PLACES_API_KEY}}
        run: echo "googlePlacesApiKey=$PLACES_API_KEY" >> local.properties

      - name: Add Branch.io API key
        env:
          BRANCH_IO_API_KEY: ${{secrets.BRANCH_IO_API_KEY}}
        run: echo "visitsBranchKey=$BRANCH_IO_API_KEY" >> local.properties

      - name: Add Hypertrack services API key
        env:
          SERVICES_API_KEY: ${{secrets.SERVICES_API_KEY}}
        run: echo "servicesApiKey=$SERVICES_API_KEY" >> local.properties

      - name: Add Hypertrack GraphQL API key
        env:
          GRAPHQL_API_KEY: ${{secrets.GRAPHQL_API_KEY}}
        run: echo "graphqlApiKey=$GRAPHQL_API_KEY" >> local.properties

      - name: Build with Gradle
        run: ./gradlew build

      # Should be a reusable workflow (release_artifact)
      - name: Assemble release APK
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v1
        with:
          name: visits-app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Assemble release AAB
        run: ./gradlew :app:bundleRelease

      - uses: actions/upload-artifact@v1
        with:
          name: visits-app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab
