name: Release Build

on:
  push:
    tags: [ v[0-9]+.[0-9]+.[0-9]+ ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Restore wrapper cache
        uses: actions/cache@v1.0.3
        with:
          path: ~/.gradle/wrapper/dists/
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      # Build itself
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      # Release artifact
      - uses: actions/upload-artifact@v1
        with:
          name: visits-app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
